apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: iac-deployer-namespace-boundary
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["namespaces"]
  matchConditions:
    - name: is-argocd-iac-deployer
      expression: 'request.userInfo.username == "system:serviceaccount:kube-system:argocd-iac-deployer"'
  validations:
    - expression: 'object.metadata.name.matches("^iac-.*$")'
      message: "argocd-iac-deployer is only authorized to manage namespaces prefixed with iac-"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: iac-deployer-namespace-boundary-binding
spec:
  policyName: iac-deployer-namespace-boundary
  validationActions: [Deny, Audit]
