apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-workloads-prod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: orders
            tenant: tenant-a
            env: prod
            port: "8082"
  template:
    metadata:
      name: "{{tenant}}-{{env}}"
      annotations:
        link.argocd.argoproj.io/external-link: "http://orders-{{env}}.localhost:{{port}}"
    spec:
      project: tenant-workloads
      info:
        - name: "Live Orders Dashboard"
          value: "http://orders-{{env}}.localhost:{{port}}"
        - name: "Central Moto Cloud"
          value: "http://localhost:5000/moto-api/"
      sources:
        - chart: message-processor
          repoURL: ghcr.io/brunobml/charts
          targetRevision: 1.0.0
          helm:
            valueFiles:
              - $values/deploy/values-{{env}}.yaml
        - repoURL: https://github.com/brunobml/orders-processor.git
          targetRevision: main
          ref: values
      destination:
        name: spoke-prod
        namespace: "{{tenant}}-{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
