apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-workloads-nonprod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: orders
            tenant: tenant-a
            env: dev
            port: "8081"
          - app: orders
            tenant: tenant-a
            env: test
            port: "8081"
  template:
    metadata:
      name: "{{app}}-{{env}}"
      labels:
        app.kubernetes.io/name: "{{app}}"
        app: "{{app}}"
        environment: "{{env}}"
        team: "e-commerce"
        tier: "backend"
        framework: "kro-ack"
      annotations:
        link.argocd.argoproj.io/external-link: "http://orders-{{env}}.localhost:{{port}}"
        link.argocd.argoproj.io/dashboard: "http://orders-{{env}}.localhost:{{port}}"
        link.argocd.argoproj.io/source-code: "https://github.com/brunobml/orders-processor"
        link.argocd.argoproj.io/platform-chart: "https://github.com/brunobml/platform-charts"
        description: "Orders processing microservice with AWS SQS & DynamoDB via Kro"
    spec:
      project: tenant-workloads
      info:
        - name: "Application"
          value: "Orders Processor"
        - name: "Environment"
          value: "{{env}}"
        - name: "Team"
          value: "E-Commerce Squad"
        - name: "Live Dashboard"
          value: "http://orders-{{env}}.localhost:{{port}}"
        - name: "Source Code"
          value: "https://github.com/brunobml/orders-processor"
        - name: "Platform Golden Chart"
          value: "ghcr.io/brunobml/charts/queue-backed-service:1.0.0"
        - name: "Central Moto Cloud"
          value: "http://localhost:5000/moto-api/"
      sources:
        - chart: queue-backed-service
          repoURL: ghcr.io/brunobml/charts
          targetRevision: 1.0.0
          helm:
            valueFiles:
              - $values/deploy/values-{{env}}.yaml
        - repoURL: https://github.com/brunobml/orders-processor.git
          targetRevision: main
          ref: values
      destination:
        name: spoke-nonprod
        namespace: "{{app}}-{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
