apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-workloads-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/brunobml/tenant-workloads.git
        revision: main
        directories:
          - path: tenants/*/prod
  template:
    metadata:
      name: "{{path[1]}}-{{path[2]}}"
      annotations:
        link.argocd.argoproj.io/external-link: "http://orders-{{path[2]}}.localhost:8082"
    spec:
      project: tenant-workloads
      info:
        - name: "Live Orders Dashboard"
          value: "http://orders-{{path[2]}}.localhost:8082"
        - name: "Central Moto Cloud"
          value: "http://localhost:5000/moto-api/"
      source:
        repoURL: https://github.com/brunobml/tenant-workloads.git
        targetRevision: main
        path: "{{path}}"
      destination:
        name: spoke-prod
        namespace: "{{path[1]}}-{{path[2]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
