apiVersion: v1
kind: Namespace
metadata:
  name: platform-reports
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    app.kubernetes.io/part-of: platform-reports
  annotations:
    services.k8s.aws/owner-account-id: "111111111111"
